#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use WaspCli\Command\{
	ProjectRenameCommand,
	ProjectNewCommand,
	CreatePostTypeCommand,
	CreateTaxonomyCommand,
	CreateMetaBoxCommand,
	CreateTermMetaCommand,
	CreateAdminPageCommand,
	CreateAdminSubPageCommand,
	CreateSettingFieldsCommand,
	CreateUserMetaCommand,
	CreateShortcodeCommand
};

$app = new Application( 'WASP CLI', '1.0.0' );
$app->add( new ProjectRenameCommand() );
$app->add( new ProjectNewCommand() );
$app->add( new CreatePostTypeCommand() );
$app->add( new CreateTaxonomyCommand() );
$app->add( new CreateMetaBoxCommand() );
$app->add( new CreateTermMetaCommand() );
$app->add( new CreateAdminPageCommand() );
$app->add( new CreateAdminSubPageCommand() );
$app->add( new CreateSettingFieldsCommand() );
$app->add( new CreateUserMetaCommand() );
$app->add( new CreateShortcodeCommand() );
$app->run();
