#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use WaspCli\Command\RenameProjectCommand;

$app = new Application( 'WASP CLI', '1.0.0' );
$app->add( new RenameProjectCommand() );
$app->run();
