<?php
namespace WaspCli\Command;

use RuntimeException;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

abstract class AbstractGeneratorCommand extends Command
{
    /** @var string */
    protected $baseDir;

    /** @var string */
    protected $namespaceRoot;

    /** @var string */
    protected $slugRoot;

    /** @var string */
    protected $textDomain;

    /** @var string */
    protected $pluginsRootDir;

    /** @var SymfonyStyle */
    protected $io;

    /** @var Filesystem */
    protected $filesystem;

    /**
     * Overrides Symfony Command initialize to configure common settings.
     */
    protected function initialize(InputInterface $input, OutputInterface $output): void
    {
        parent::initialize($input, $output);

        $this->io         = new SymfonyStyle($input, $output);
        $this->filesystem = new Filesystem();

        // Project root folder (two levels up: cli/Command → cli → /root)
        $this->baseDir = realpath(__DIR__ . '/../../');
        if ($this->baseDir === false) {
            throw new RuntimeException('Unable to resolve base directory.');
        }

        $this->pluginsRootDir = realpath($this->baseDir . '/..');
        if ($this->pluginsRootDir === false) {
            throw new RuntimeException('Unable to resolve plugins root directory.');
        }

        // Read static configuration (generated by project:rename)
        $configPath = $this->baseDir . '/cli/config.json';
        if (! file_exists($configPath)) {
            throw new RuntimeException("Config not found at $configPath. Run project:rename first.");
        }
        $config = json_decode(file_get_contents($configPath), true);
        if (! is_array($config)) {
            throw new RuntimeException("JSON at $configPath is not valid.");
        }

        $this->namespaceRoot = (string) ($config['namespace']    ?? 'WASP');
        $this->slugRoot      = (string) ($config['slug']         ?? 'wasp');
        $this->textDomain    = (string) ($config['text_domain']  ?? 'wasp');

        if ($this->namespaceRoot === '') {
            throw new RuntimeException('Invalid config: namespace cannot be empty.');
        }
        if (! preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/', $this->slugRoot)) {
            throw new RuntimeException('Invalid config: slug must use lowercase letters, numbers and dashes.');
        }
        if ($this->textDomain === '') {
            throw new RuntimeException('Invalid config: text_domain cannot be empty.');
        }
    }

    /**
     * Converts "Foo Bar" to "foo-bar"
     */
    protected function slugify(string $text): string
    {
        $original = $text;
        $translit = iconv('UTF-8', 'ASCII//TRANSLIT', $text);
        if ($translit !== false) {
            $text = $translit;
        }

        $text = preg_replace('/[^\p{L}\p{Nd}]+/u', '-', $text);
        $text = preg_replace('/-+/', '-', $text);
        $slug = strtolower(trim($text, '-'));

        if ($slug === '') {
            throw new RuntimeException(sprintf('Cannot generate a valid slug from "%s".', $original));
        }

        return $slug;
    }

    /**
     * Absolute path to a stub inside cli/stubs/
     */
    protected function getStubPath(string $stubName): string
    {
        return $this->baseDir . '/cli/stubs/' . $stubName . '.stub';
    }

    /**
     * Loads the content of a stub. Throws exception if it does not exist.
     */
    protected function loadStub(string $stubName): string
    {
        $stubPath = $this->getStubPath($stubName);
        if (! file_exists($stubPath)) {
            throw new RuntimeException("Stub not found: $stubPath");
        }
        return file_get_contents($stubPath);
    }

    /**
     * Replaces all keys from $replacements array in the stub content.
     * Example: if $replacements = ['{{SLUG}}' => 'my-slug'], it performs str_replace.
     */
    protected function renderStub(string $stubContent, array $replacements): string
    {
        return str_replace(array_keys($replacements), array_values($replacements), $stubContent);
    }

    /**
     * Generates a file at $destinationPath using the stub $stubName and
     * replacing placeholders using $replacements. If it already exists, show error.
     */
    protected function createFileFromStub(
        string $stubName,
        string $destinationDir,
        string $fileName,
        array $replacements
    ): string {
        // 1) Ensure the destination directory exists
        if (! is_dir($destinationDir)) {
            $this->filesystem->mkdir($destinationDir, 0755);
        }

        $fullPath = rtrim($destinationDir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $fileName;

        // 2) If the file already exists, fail
        if (file_exists($fullPath)) {
            $this->io->error("File already exists: $fullPath");
            throw new RuntimeException("Not overwritten: $fullPath");
        }

        // 3) Load stub, render and write
        $stubContent = $this->loadStub($stubName);
        $finalContent = $this->renderStub($stubContent, $replacements);

        $bytes = file_put_contents($fullPath, $finalContent, LOCK_EX);
        if ($bytes === false) {
            throw new RuntimeException("Unable to write generated file: $fullPath");
        }

        return $fullPath;
    }

    /**
     * Resolves plugin context for current project or a child project.
     *
     * @return array{
     *     plugin_base_dir:string,
     *     project_slug:string,
     *     namespace_prefix:string,
     *     text_domain:string
     * }
     */
    protected function resolveProjectContext(?string $projectArg): array
    {
        if ($projectArg === null || $projectArg === '') {
            return [
                'plugin_base_dir'  => $this->baseDir,
                'project_slug'     => $this->slugRoot,
                'namespace_prefix' => $this->namespaceRoot,
                'text_domain'      => $this->textDomain,
            ];
        }

        if (! preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/', $projectArg)) {
            throw new RuntimeException(
                "Invalid project slug \"$projectArg\". Use lowercase letters, numbers and dashes only."
            );
        }

        $expectedPath = $this->baseDir . '/../' . $projectArg;
        $childDir = realpath($expectedPath);
        if (! $childDir || ! is_dir($childDir)) {
            throw new RuntimeException("Project not found: $projectArg (expected at $expectedPath)");
        }

        $pluginsRoot = rtrim($this->pluginsRootDir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;
        $resolvedChildDir = rtrim($childDir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;
        if (strpos($resolvedChildDir, $pluginsRoot) !== 0) {
            throw new RuntimeException("Project path is outside plugins root and is not allowed: $childDir");
        }

        return [
            'plugin_base_dir'  => rtrim($childDir, DIRECTORY_SEPARATOR),
            'project_slug'     => $projectArg,
            'namespace_prefix' => $this->namespaceFromSlug($projectArg),
            'text_domain'      => $projectArg,
        ];
    }

    /**
     * Converts a slug like "my-plugin" to "MyPlugin" for namespace declarations.
     */
    protected function namespaceFromSlug(string $slug): string
    {
        $parts = explode('-', $slug);
        $namespace = '';

        foreach ($parts as $part) {
            if ($part === '') {
                continue;
            }
            $namespace .= ucfirst(strtolower($part));
        }

        if ($namespace === '') {
            throw new RuntimeException("Cannot generate namespace from slug \"$slug\".");
        }

        if (preg_match('/^\d/', $namespace)) {
            $namespace = 'Project' . $namespace;
        }

        return $namespace;
    }

    /**
     * Appends an instance line to loader file when missing.
     * Returns true if line was appended, false if it was already present.
     */
    protected function appendLineToLoader(string $loaderFile, string $line): bool
    {
        if (! file_exists($loaderFile)) {
            throw new RuntimeException("Cannot register class. Loader not found: $loaderFile");
        }
        if (! is_writable($loaderFile)) {
            throw new RuntimeException("Cannot register class. Loader is not writable: $loaderFile");
        }

        $content = file_get_contents($loaderFile);
        if ($content === false) {
            throw new RuntimeException("Cannot read loader file: $loaderFile");
        }

        if (strpos($content, $line) !== false) {
            return false;
        }

        $prefix = '';
        if ($content !== '' && substr($content, -1) !== "\n") {
            $prefix = PHP_EOL;
        }

        $result = file_put_contents($loaderFile, $prefix . $line, FILE_APPEND | LOCK_EX);
        if ($result === false) {
            throw new RuntimeException("Cannot write loader file: $loaderFile");
        }

        return true;
    }
}
